### PR TITLE
pale rain media

### PR DESCRIPTION
**Pull request by PhantomRuby**
media for [pale rain](https://github.com/hsmusic/hsmusic-data/pull/540)

also includes cover for pokemon unbound since i dont use branches on media, actual data will come later (100/187 album tracks are done so far - if you really want you can check progress on my fork i guess) stay tune : )

### CODE REVIEW

**Comment by towerofnix** [comment]
Merging manually to get just the pale-rain commit!

**Comment by PhantomRuby** [comment]
the unbound cover would be added in a later push regardless, but I guess if you wanna keep things overseeable like that that's fair^^

**Comment by towerofnix** [comment]
Misplaced (i.e. unexpected) media files are automatically flagged by hsmusic, so better not to merge Unbound assets til the data file is set!

**Comment by PhantomRuby** [comment]
that's completely fair!

**Pull request closed without merging**
